apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecrafts.minecraft.dentrassi.de
spec:

  group: minecraft.dentrassi.de
  scope: Namespaced

  names:
    plural: minecrafts
    singular: minecraft
    kind: Minecraft

  versions:
    - name: v1alpha1
      served: true
      storage: true

      subresources:
        status: {}

      schema:
        openAPIV3Schema:
          description: Minecraft deploys a new instance of a Minecraft server
          type: object
          properties:

            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string

            spec:
              type: object
              properties:

            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
